{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: bdbe50e2e22a1c71acaa0c8ba6efaadd58882e5a5978737a44a4c4b10d304c92
  patches:
    - patches/0001-remove-opentelemetry-test-dependencies.patch

build:
  skip: True        # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - m2-patch      # [win]
    - patch         # [not win]
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - opentelemetry-proto =={{ version }}

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
    - python -m unittest discover tests
  requires:
    - pip
    - opentelemetry-api =={{ version }}
    - opentelemetry-sdk =={{ version }}
  source_files:
    - tests

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  home: https://opentelemetry.io/
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-common
  doc_url: https://opentelemetry.io/docs/
  description: This library is provided as a convenience to encode to Protobuf. 

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
