{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_common-{{ version }}.tar.gz
  sha256: 71ae2f81bc6d6fe408d06388826edc8933759b2ca3a97d24054507dc7cfce52d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - opentelemetry-proto =={{ version }}
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<3.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  home: https://opentelemetry.io/

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
