{% set name = "opentelemetry-exporter-otlp-proto-common" %}
{% set version = "1.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: c87a1bdd9f41fdc408d9cc9367bb53f8d2602829659f2b90be9f9d79d0bfe62c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-proto =={{ version }}

# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
{% set ignore_tests = " --ignore=tests/test_metrics_encoder.py" %}

test:
  source_files:
    - tests
  imports:
    - opentelemetry.exporter.otlp.proto.common
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest >=7.4.4
    - opentelemetry-api =={{ version }}
    - opentelemetry-sdk =={{ version }}
    - opentelemetry-semantic-conventions ==0.58b0

about:
  summary: OpenTelemetry Protobuf encoding
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  home: https://opentelemetry.io/
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-common
  doc_url: https://opentelemetry.io/docs/
  description: This library is provided as a convenience to encode to Protobuf. 

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
